### ISSUE TITLE
Vertical mode.....

### ISSUE THREAD

**Issue by LeePC** [jtl1207/comic-translation#8]
Vertical mode is not working properly.
I hope you can fix it.

**Comment by jtl1207** [comment]
Can English be vertical?
I turned off the vertical mode for English

If you really need
You can open  .\resources\main  with  notepad
Find [   if self.var.word_way == 2 or self.var.word_language == 'en' or self.var.word_language == 'ko':   ]
and replace with  [   if self.var.word_way == 2:   ]

There are a total of 2 changes to be made in the file

**Comment by jtl1207** [comment]
If you need a few letters vertically
You can try a very tall and narrow rectangle

**Comment by LeePC** [comment]
War:현재 언어는 세로 문자를 지원하지 않습니다.
Even though I did that, it doesn't work.

**Comment by LeePC** [comment]
I'm sorry. I fixed it.
