### ISSUE TITLE
program execution error

### ISSUE THREAD

**Issue by YTOAA** [jtl1207/comic-translation#9]
First of all, I will inform you that it is a laptop that does not have an external graphics card. The installation proceeds without any errors, and if you run the program after installation, the program will end with the following errors.
It was executed in the latest version of 1.2.1 and Korean patch was also conducted.
It ran in a Windows 10 64-bit environment.
Add the contents. When you overwrite the Korean patch file as it is, the error occurs and ends. If you don't overwrite the Korean patch, it won't end.
Also, is the overall translation not activated?
Traceback (most recent call last):
  File "E:\comic\resources\main.py", line 965, in config_read
    config.read('config.ini')
  File "E:\comic\Python\lib\configparser.py", line 697, in read
    self._read(fp, filename)
  File "E:\comic\Python\lib\configparser.py", line 1017, in _read
    for lineno, line in enumerate(fp, start=1):
UnicodeDecodeError: 'cp949' codec can't decode byte 0xc9 in position 74: illegal multibyte sequence

**Comment by LeePC** [comment]
config.ini file open
Please change the font name.

**Comment by jtl1207** [comment]
You can open .\resources\main with notepad
Find [ config.read('config.ini') ]
and replace with [ config.read('config.ini', encoding='gbk') ]

This is because the file uses Simplified Chinese encoding
I will fix this bug in the next version

**Comment by YTOAA** [comment]
Thank you. I fixed the error. Has the entire translation function not been activated yet?

**Comment by YTOAA** [comment]
> 메모장 찾기 [ config.read('config.ini') ] 로 .\resources\main을 열고 [ config.read('config.ini', encoding='gbk') ]로 바꿀 수 있습니다.
> 
> 파일이 중국어 간체 인코딩을 사용하기 때문 입니다 이 버그는 다음 버전에서 수정하겠습니다 파일 내용을 직접 수정해 볼 수도 있습니다

**Comment by jtl1207** [comment]
yes

Because the translation is terrible, at least the Chinese language is very poor
